In [6]:
# ----------
#
# In this exercise, you will update the perceptron class so that it can update
# its weights.
#
# Finish writing the update() method so that it updates the weights according
# to the perceptron update rule.
# 
# ----------

import numpy as np


class Perceptron:
    """
    This class models an artificial neuron with step activation function.
    """

    def __init__(self, weights = np.array([1]), threshold = 0):
        """
        Initialize weights and threshold based on input arguments. Note that no
        type-checking is being performed here for simplicity.
        """
        self.weights = weights * 1.0
        self.threshold = threshold


    def activate(self, values):
        """
        Takes in @param values, a list of numbers equal to length of weights.
        @return the output of a threshold perceptron with given inputs based on
        perceptron weights and threshold.
        """
               
        # First calculate the strength with which the perceptron fires
        strength = np.dot(values,self.weights)
        
        # Then return 0 or 1 depending on strength compared to threshold  
        return int(strength > self.threshold)


    def update(self, values, train, eta=.1):
        """
        Takes in a 2D array @param values consisting of a LIST of inputs and a
        1D array @param train, consisting of a corresponding list of expected
        outputs. Updates internal weights according to the perceptron training
        rule using these values and an optional learning rate, @param eta.
        """

        # method 1
        """
        for i, item in enumerate(values):
            train_hat = self.activate(item)
            self.weights += (eta * (train[i] - train_hat)) * item

        """
        # method 2
        for i, item in enumerate(values):
            train_hat = self.activate(item)
            for j, val in enumerate(item):
                self.weights[j] += eta * (train[i] - train_hat) * val

        return self.weights
            # TODO: update self.weights based on prediction accuracy, learning
            # rate and input value

In [10]:
# check how the perceptron get updated

p1 = Perceptron(np.array([3,0,2]),0)
p2 = Perceptron(np.array([3,0,2]),0)
p3 = Perceptron(np.array([3,0,2]),0)

p1.update(np.array([[2,-2,4]]),np.array([0]))
p2.update(np.array([[2,-2,4],[-1,-3,2]]),np.array([0,1]))
p3.update(np.array([[2,-2,4],[-1,-3,2],[0,2,1]]),np.array([0,1,0]))

print (p1.weights)
print (p2.weights)
print (p3.weights)

[ 2.8  0.2  1.6]
[ 2.7 -0.1  1.8]
[ 2.7 -0.3  1.7]


### Layered network example

A layered network represents as follow:

[[ node, node, node],   # input  layer 

[node, node],           # hidden layer 

[node]]                 # output layer 

Give the weights for the hidden layer of [1,1,-5], and [3,-4,2] and weights for the output layer of [2,-1], what will this network output for inputs [1,2,3]?

In [14]:
# hiden layers

output = np.dot([np.dot([1,2,3], [1,1,-5]), np.dot([1,2,3], [3,-4,2])], [2,-1])
print output

-25


### Linear Representation Power

Given the following network, where each node simply passes along the dot product of its inputs with its weights, write down the weights of a single linear node that computes the same function.

[[input, input],
[[3,2], [-1,4], [3,-5]],
[[1,2,-1]]]

In [17]:
# Try setting all the inputs to zero, then modifying one input to 1 to get the slopes
[np.dot([np.dot([1,0], [3,2]), np.dot([1,0], [-1,4]),  np.dot([1,0], [3,-5])], [1, 2,-1]),
np.dot([np.dot([0,1], [3,2]), np.dot([0,1], [-1,4]),  np.dot([0,1], [3,-5])], [1, 2,-1])]

[-2, 15]